travis:
  secure:
    BINSTAR_TOKEN: IN/NBSyujqDOT08D/BkHUHyyyTwH1dE9kyIIcbDn8sem28Jk0uDo/ZTjKiKTsIfkEmkxa9ORFgwAfppF+Gcs0wukfG1FgdcTt1g0Ps+UZu2smNUuZRyxEWajHx+o3Npjp7VKmpQk9wMDKuVU5lbr8xWp0PilyOG/wUTXKT4j6xSumYt0tKaB8NbE2itHtH37+HlArOYhwps49OBatMgsFBQepZtAVieRwW7hip2gnI+BJlWHekElr2fkR6hlHtkJOWLG9uAHPtAohkhC47+H4t+mhoomBpdGIlJ+j13K9xEVb6vnbV3ksedtN0lW5cb9LaZCkBstTRglnWON8NN/RUnf3BlNWSVnyOyDpml3l/ZRHMQ/DxOHmf21WdYvlgaF5lIZxVIdezpm45WC7cVHTRllNbUKP2Nfr0ULHRn/EtOOBo+p7qCXNzJPFoQhvsZ0AGSt3SyONBCokT5XBvRtIucn0Ygmo7E/sQr9DBoFijV8KQ/2xOuIExl8b1WmgIoFdFWiJWqNqIooPjT+Vbwui6CIrPwZpo4CPF+Pdjk2DdFVUU9Hvof8NTmzNoRYoCl01EyXfsyBj9BlTCuc1umcaw9F6mogLg0ile/NUo23ZCgcXxPxz7sQG7ntxseoCIa9bmPdDBYJ+QUz6ExiBRRJ0nQ5gQfiTik1rwNCsa1AJJY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
