travis:
  secure:
    BINSTAR_TOKEN: JlUS3mn3HQ9SQ9EDpUXAfrMWjmr57jlVAU7oYSr53CznCEmaZ5RKAoV2MCwUu+Fv5BjyhkVw/bXLJoNAmht8Kd4myVWmNTXKCiGG7b0cHI/USagZKs6IcpvPf8kKRL3HDGHeAP3BbtC8GDYUmFRP9/MHRufB5mHiBygiGJfBuODy0Zm0JGqQ0gHKywvh5Jt53+kU8fr4nohfsU4zx6e8/ShGtBcz75Y+N4KGl7v3VTFFb0RF77Gp5hfGQ8FXjQApK8KwU2Qyom2qKeG4AkMC1xnVTDsHSryW64QYut9Lnu9SwTRbR8SbY8al9LtBOPsbiKXEZAFuTfThk54TeWxONWcPPXlH3GYclpZr8vJw2em/oki1d/3x/QfRghGWgB+bJbt0ylItk2kslhIxsTjdYxSmBb+JK1OJkuuaAp85SUSopWUD1DrHmJJ/VXoKZAJ66DfhtAwYsM/ecjpx+fW8MHGu362EgEMu0KXZTnwIRbipwaiZQrB+03dfrNLFq/0goAFlc1Im6H6LN71JcCXv8PLGWZLP1t0iTqW8G2++duu7O/nokd4QDj+R4rz1oyVNlatsI2b6Ec8Mh+AXBK3ce+kAnlBC0PGIfGnGklUkPjF7FX5+Y5sHtaNOQCNXa5XWpUUew+j3OuuhAJffz0+boU2e1gaE38b1Zv9iKbTkr0A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
